function makeDanawaCpuSample({
  id,
  brand,
  name,
  socket,
  generation,
  role,
  cores,
  threads,
  boostGhz,
  tdpW,
  hasIntegratedGraphics,
  coolerIncluded,
  sourceProductId,
  productUrl,
  price,
  rawSpecText,
}) {
  const searchUrl = `https://search.danawa.com/dsearch.php?query=${encodeURIComponent(name)}`;
  return {
    id,
    category: "cpu",
    name,
    chipBrand: brand,
    socket,
    generation,
    role,
    specs: {
      cores,
      threads,
      boostGhz,
      tdpW,
      hasIntegratedGraphics,
      coolerIncluded,
    },
    sourceData: {
      source: "danawa",
      sourceProductId: sourceProductId || `search_${id}`,
      productUrl: productUrl || searchUrl,
      price: price ?? null,
      priceStatus: price ? "samplePrice" : "unknown",
      crawledAt: "2026-06-04",
      rawName: name,
      rawSpecText,
    },
  };
}

const danawaCpuSampleProducts = [
  makeDanawaCpuSample({
    id: "danawa_cpu_intel_core_i5_12400f",
    brand: "Intel",
    name: "인텔 코어i5-12세대 12400F (엘더레이크)",
    socket: "LGA1700",
    generation: "12세대 Alder Lake",
    role: "가성비",
    cores: 6,
    threads: 12,
    boostGhz: 4.4,
    tdpW: 65,
    hasIntegratedGraphics: false,
    coolerIncluded: true,
    rawSpecText:
      "인텔(소켓1700) / 6코어 / 12스레드 / 최대 클럭: 4.4GHz / PBP 65W / 내장그래픽 미탑재 / 쿨러 포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_intel_core_i5_13400f",
    brand: "Intel",
    name: "인텔 코어i5-13세대 13400F (랩터레이크)",
    socket: "LGA1700",
    generation: "13세대 Raptor Lake",
    role: "가성비",
    cores: 10,
    threads: 16,
    boostGhz: 4.6,
    tdpW: 65,
    hasIntegratedGraphics: false,
    coolerIncluded: true,
    rawSpecText:
      "인텔(소켓1700) / P6+E4코어 / 16스레드 / 최대 클럭: 4.6GHz / PBP 65W / 내장그래픽 미탑재 / 쿨러 포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_intel_core_i5_14400f",
    brand: "Intel",
    name: "인텔 코어i5-14세대 14400F (랩터레이크 리프레시)",
    socket: "LGA1700",
    generation: "14세대 Raptor Lake Refresh",
    role: "가성비",
    cores: 10,
    threads: 16,
    boostGhz: 4.7,
    tdpW: 65,
    hasIntegratedGraphics: false,
    coolerIncluded: true,
    rawSpecText:
      "인텔(소켓1700) / P6+E4코어 / 16스레드 / 최대 클럭: 4.7GHz / PBP 65W / 내장그래픽 미탑재 / 쿨러 포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_intel_core_i5_14500",
    brand: "Intel",
    name: "인텔 코어i5-14세대 14500 (랩터레이크 리프레시)",
    socket: "LGA1700",
    generation: "14세대 Raptor Lake Refresh",
    role: "가성비",
    cores: 14,
    threads: 20,
    boostGhz: 5.0,
    tdpW: 65,
    hasIntegratedGraphics: true,
    coolerIncluded: true,
    rawSpecText:
      "인텔(소켓1700) / P6+E8코어 / 20스레드 / 최대 클럭: 5.0GHz / PBP 65W / 인텔 UHD 그래픽 / 쿨러 포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_intel_core_i5_14600k",
    brand: "Intel",
    name: "인텔 코어i5-14세대 14600K (랩터레이크 리프레시)",
    socket: "LGA1700",
    generation: "14세대 Raptor Lake Refresh",
    role: "가성비 고성능",
    cores: 14,
    threads: 20,
    boostGhz: 5.3,
    tdpW: 125,
    hasIntegratedGraphics: true,
    coolerIncluded: false,
    sourceProductId: "28799654",
    productUrl: "https://prod.danawa.com/info/?pcode=28799654",
    price: 374990,
    rawSpecText:
      "인텔(소켓1700) / P6+E8코어 / 20스레드 / 최대 클럭: 5.3GHz / PBP-MTP: 125-181W / 인텔 UHD 770 / 퀵싱크 / 쿨러 미포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_intel_core_i5_14600kf",
    brand: "Intel",
    name: "인텔 코어i5-14세대 14600KF (랩터레이크 리프레시)",
    socket: "LGA1700",
    generation: "14세대 Raptor Lake Refresh",
    role: "가성비 고성능",
    cores: 14,
    threads: 20,
    boostGhz: 5.3,
    tdpW: 125,
    hasIntegratedGraphics: false,
    coolerIncluded: false,
    rawSpecText:
      "인텔(소켓1700) / P6+E8코어 / 20스레드 / 최대 클럭: 5.3GHz / PBP-MTP: 125-181W / 내장그래픽 미탑재 / 쿨러 미포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_intel_core_i7_14700f",
    brand: "Intel",
    name: "인텔 코어i7-14세대 14700F (랩터레이크 리프레시)",
    socket: "LGA1700",
    generation: "14세대 Raptor Lake Refresh",
    role: "영상·멀티",
    cores: 20,
    threads: 28,
    boostGhz: 5.4,
    tdpW: 65,
    hasIntegratedGraphics: false,
    coolerIncluded: true,
    rawSpecText:
      "인텔(소켓1700) / P8+E12코어 / 28스레드 / 최대 클럭: 5.4GHz / PBP 65W / 내장그래픽 미탑재 / 쿨러 포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_intel_core_i7_14700k",
    brand: "Intel",
    name: "인텔 코어i7-14세대 14700K (랩터레이크 리프레시)",
    socket: "LGA1700",
    generation: "14세대 Raptor Lake Refresh",
    role: "영상·멀티",
    cores: 20,
    threads: 28,
    boostGhz: 5.6,
    tdpW: 125,
    hasIntegratedGraphics: true,
    coolerIncluded: false,
    rawSpecText:
      "인텔(소켓1700) / P8+E12코어 / 28스레드 / 최대 클럭: 5.6GHz / PBP-MTP: 125-253W / 인텔 UHD 770 / 쿨러 미포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_intel_core_i9_14900k",
    brand: "Intel",
    name: "인텔 코어i9-14세대 14900K (랩터레이크 리프레시)",
    socket: "LGA1700",
    generation: "14세대 Raptor Lake Refresh",
    role: "고성능",
    cores: 24,
    threads: 32,
    boostGhz: 6.0,
    tdpW: 125,
    hasIntegratedGraphics: true,
    coolerIncluded: false,
    rawSpecText:
      "인텔(소켓1700) / P8+E16코어 / 32스레드 / 최대 클럭: 6.0GHz / PBP-MTP: 125-253W / 인텔 UHD 770 / 쿨러 미포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_intel_core_ultra_5_225f",
    brand: "Intel",
    name: "인텔 코어 Ultra 5 225F (애로우레이크)",
    socket: "LGA1851",
    generation: "Core Ultra Series 2 Arrow Lake",
    role: "최신 가성비",
    cores: 10,
    threads: 10,
    boostGhz: 4.9,
    tdpW: 65,
    hasIntegratedGraphics: false,
    coolerIncluded: true,
    rawSpecText:
      "인텔(소켓1851) / P6+E4코어 / 10스레드 / 최대 클럭: 4.9GHz / PBP 65W / 내장그래픽 미탑재 / 쿨러 포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_intel_core_ultra_5_245k",
    brand: "Intel",
    name: "인텔 코어 Ultra 5 245K (애로우레이크)",
    socket: "LGA1851",
    generation: "Core Ultra Series 2 Arrow Lake",
    role: "최신 균형",
    cores: 14,
    threads: 14,
    boostGhz: 5.2,
    tdpW: 125,
    hasIntegratedGraphics: true,
    coolerIncluded: false,
    rawSpecText:
      "인텔(소켓1851) / P6+E8코어 / 14스레드 / 최대 클럭: 5.2GHz / PBP 125W / 인텔 그래픽 / NPU 탑재 / 쿨러 미포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_intel_core_ultra_7_265",
    brand: "Intel",
    name: "인텔 코어 Ultra 7 265 (애로우레이크)",
    socket: "LGA1851",
    generation: "Core Ultra Series 2 Arrow Lake",
    role: "최신 균형",
    cores: 20,
    threads: 20,
    boostGhz: 5.3,
    tdpW: 65,
    hasIntegratedGraphics: true,
    coolerIncluded: true,
    rawSpecText:
      "인텔(소켓1851) / P8+E12코어 / 20스레드 / 최대 클럭: 5.3GHz / PBP 65W / 인텔 그래픽 / NPU 탑재 / 쿨러 포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_intel_core_ultra_7_265k",
    brand: "Intel",
    name: "인텔 코어 Ultra 7 265K (애로우레이크)",
    socket: "LGA1851",
    generation: "Core Ultra Series 2 Arrow Lake",
    role: "최신 영상·멀티",
    cores: 20,
    threads: 20,
    boostGhz: 5.5,
    tdpW: 125,
    hasIntegratedGraphics: true,
    coolerIncluded: false,
    rawSpecText:
      "인텔(소켓1851) / P8+E12코어 / 20스레드 / 최대 클럭: 5.5GHz / PBP 125W / 인텔 그래픽 / NPU 탑재 / 쿨러 미포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_intel_core_ultra_9_285k",
    brand: "Intel",
    name: "인텔 코어 Ultra 9 285K (애로우레이크)",
    socket: "LGA1851",
    generation: "Core Ultra Series 2 Arrow Lake",
    role: "최신 고성능",
    cores: 24,
    threads: 24,
    boostGhz: 5.7,
    tdpW: 125,
    hasIntegratedGraphics: true,
    coolerIncluded: false,
    rawSpecText:
      "인텔(소켓1851) / P8+E16코어 / 24스레드 / 최대 클럭: 5.7GHz / PBP 125W / 인텔 그래픽 / NPU 탑재 / 쿨러 미포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_intel_core_ultra_9_285",
    brand: "Intel",
    name: "인텔 코어 Ultra 9 285 (애로우레이크)",
    socket: "LGA1851",
    generation: "Core Ultra Series 2 Arrow Lake",
    role: "최신 고성능",
    cores: 24,
    threads: 24,
    boostGhz: 5.6,
    tdpW: 65,
    hasIntegratedGraphics: true,
    coolerIncluded: true,
    rawSpecText:
      "인텔(소켓1851) / P8+E16코어 / 24스레드 / 최대 클럭: 5.6GHz / PBP 65W / 인텔 그래픽 / NPU 탑재 / 쿨러 포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_amd_ryzen_5_5600",
    brand: "AMD",
    name: "AMD 라이젠5-4세대 5600 (버미어)",
    socket: "AM4",
    generation: "Zen3",
    role: "가성비",
    cores: 6,
    threads: 12,
    boostGhz: 4.4,
    tdpW: 65,
    hasIntegratedGraphics: false,
    coolerIncluded: true,
    rawSpecText:
      "AMD(소켓AM4) / 6코어 / 12스레드 / 최대 클럭: 4.4GHz / TDP 65W / 내장그래픽 미탑재 / Wraith Stealth 쿨러 포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_amd_ryzen_7_5700x3d",
    brand: "AMD",
    name: "AMD 라이젠7-4세대 5700X3D (버미어)",
    socket: "AM4",
    generation: "Zen3 3D V-Cache",
    role: "AM4 가성비",
    cores: 8,
    threads: 16,
    boostGhz: 4.1,
    tdpW: 105,
    hasIntegratedGraphics: false,
    coolerIncluded: false,
    rawSpecText:
      "AMD(소켓AM4) / 8코어 / 16스레드 / 최대 클럭: 4.1GHz / TDP 105W / 3D V캐시 / 내장그래픽 미탑재 / 쿨러 미포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_amd_ryzen_5_7500f",
    brand: "AMD",
    name: "AMD 라이젠5-5세대 7500F (라파엘)",
    socket: "AM5",
    generation: "Zen4",
    role: "가성비",
    cores: 6,
    threads: 12,
    boostGhz: 5.0,
    tdpW: 65,
    hasIntegratedGraphics: false,
    coolerIncluded: true,
    sourceProductId: "21694499",
    productUrl: "https://prod.danawa.com/info/?pcode=21694499",
    rawSpecText:
      "AMD(소켓AM5) / 6코어 / 12스레드 / 최대 클럭: 5.0GHz / TDP 65W / PPT 88W / PCIe5.0 / 내장그래픽 미탑재 / Wraith Stealth 포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_amd_ryzen_5_7600",
    brand: "AMD",
    name: "AMD 라이젠5-5세대 7600 (라파엘)",
    socket: "AM5",
    generation: "Zen4",
    role: "가성비",
    cores: 6,
    threads: 12,
    boostGhz: 5.1,
    tdpW: 65,
    hasIntegratedGraphics: true,
    coolerIncluded: true,
    rawSpecText:
      "AMD(소켓AM5) / 6코어 / 12스레드 / 최대 클럭: 5.1GHz / TDP 65W / AMD 라데온 그래픽 / Wraith Stealth 포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_amd_ryzen_5_7600x",
    brand: "AMD",
    name: "AMD 라이젠5-5세대 7600X (라파엘)",
    socket: "AM5",
    generation: "Zen4",
    role: "가성비 고성능",
    cores: 6,
    threads: 12,
    boostGhz: 5.3,
    tdpW: 105,
    hasIntegratedGraphics: true,
    coolerIncluded: false,
    rawSpecText:
      "AMD(소켓AM5) / 6코어 / 12스레드 / 최대 클럭: 5.3GHz / TDP 105W / AMD 라데온 그래픽 / 쿨러 미포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_amd_ryzen_7_7700",
    brand: "AMD",
    name: "AMD 라이젠7-5세대 7700 (라파엘)",
    socket: "AM5",
    generation: "Zen4",
    role: "균형",
    cores: 8,
    threads: 16,
    boostGhz: 5.3,
    tdpW: 65,
    hasIntegratedGraphics: true,
    coolerIncluded: true,
    rawSpecText:
      "AMD(소켓AM5) / 8코어 / 16스레드 / 최대 클럭: 5.3GHz / TDP 65W / AMD 라데온 그래픽 / Wraith Prism 포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_amd_ryzen_7_7700x",
    brand: "AMD",
    name: "AMD 라이젠7-5세대 7700X (라파엘)",
    socket: "AM5",
    generation: "Zen4",
    role: "균형",
    cores: 8,
    threads: 16,
    boostGhz: 5.4,
    tdpW: 105,
    hasIntegratedGraphics: true,
    coolerIncluded: false,
    rawSpecText:
      "AMD(소켓AM5) / 8코어 / 16스레드 / 최대 클럭: 5.4GHz / TDP 105W / AMD 라데온 그래픽 / 쿨러 미포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_amd_ryzen_7_7800x3d",
    brand: "AMD",
    name: "AMD 라이젠7-5세대 7800X3D (라파엘)",
    socket: "AM5",
    generation: "Zen4 3D V-Cache",
    role: "인기 고성능",
    cores: 8,
    threads: 16,
    boostGhz: 5.0,
    tdpW: 120,
    hasIntegratedGraphics: true,
    coolerIncluded: false,
    sourceProductId: "19627934",
    productUrl: "https://prod.danawa.com/info/?pcode=19627934",
    rawSpecText:
      "AMD(소켓AM5) / 8코어 / 16스레드 / 최대 클럭: 5.0GHz / L3 캐시 96MB / TDP 120W / PPT 162W / AMD 라데온 그래픽 / 3D V캐시 / 쿨러 미포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_amd_ryzen_9_7900",
    brand: "AMD",
    name: "AMD 라이젠9-5세대 7900 (라파엘)",
    socket: "AM5",
    generation: "Zen4",
    role: "멀티 가성비",
    cores: 12,
    threads: 24,
    boostGhz: 5.4,
    tdpW: 65,
    hasIntegratedGraphics: true,
    coolerIncluded: true,
    rawSpecText:
      "AMD(소켓AM5) / 12코어 / 24스레드 / 최대 클럭: 5.4GHz / TDP 65W / AMD 라데온 그래픽 / 쿨러 포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_amd_ryzen_9_7900x",
    brand: "AMD",
    name: "AMD 라이젠9-5세대 7900X (라파엘)",
    socket: "AM5",
    generation: "Zen4",
    role: "영상·멀티",
    cores: 12,
    threads: 24,
    boostGhz: 5.6,
    tdpW: 170,
    hasIntegratedGraphics: true,
    coolerIncluded: false,
    rawSpecText:
      "AMD(소켓AM5) / 12코어 / 24스레드 / 최대 클럭: 5.6GHz / TDP 170W / AMD 라데온 그래픽 / 쿨러 미포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_amd_ryzen_5_9600x",
    brand: "AMD",
    name: "AMD 라이젠5-6세대 9600X (그래니트 릿지)",
    socket: "AM5",
    generation: "Zen5",
    role: "최신 가성비",
    cores: 6,
    threads: 12,
    boostGhz: 5.4,
    tdpW: 65,
    hasIntegratedGraphics: true,
    coolerIncluded: false,
    rawSpecText:
      "AMD(소켓AM5) / 6코어 / 12스레드 / 최대 클럭: 5.4GHz / TDP 65W / AMD 라데온 그래픽 / 쿨러 미포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_amd_ryzen_7_9700x",
    brand: "AMD",
    name: "AMD 라이젠7-6세대 9700X (그래니트 릿지)",
    socket: "AM5",
    generation: "Zen5",
    role: "최신 균형",
    cores: 8,
    threads: 16,
    boostGhz: 5.5,
    tdpW: 65,
    hasIntegratedGraphics: true,
    coolerIncluded: false,
    rawSpecText:
      "AMD(소켓AM5) / 8코어 / 16스레드 / 최대 클럭: 5.5GHz / TDP 65W / AMD 라데온 그래픽 / 쿨러 미포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_amd_ryzen_7_9800x3d",
    brand: "AMD",
    name: "AMD 라이젠7-6세대 9800X3D (그래니트 릿지)",
    socket: "AM5",
    generation: "Zen5 3D V-Cache",
    role: "최신 인기 고성능",
    cores: 8,
    threads: 16,
    boostGhz: 5.2,
    tdpW: 120,
    hasIntegratedGraphics: true,
    coolerIncluded: false,
    rawSpecText:
      "AMD(소켓AM5) / 8코어 / 16스레드 / 최대 클럭: 5.2GHz / TDP 120W / 3D V캐시 / AMD 라데온 그래픽 / 쿨러 미포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_amd_ryzen_9_9900x",
    brand: "AMD",
    name: "AMD 라이젠9-6세대 9900X (그래니트 릿지)",
    socket: "AM5",
    generation: "Zen5",
    role: "최신 영상·멀티",
    cores: 12,
    threads: 24,
    boostGhz: 5.6,
    tdpW: 120,
    hasIntegratedGraphics: true,
    coolerIncluded: false,
    rawSpecText:
      "AMD(소켓AM5) / 12코어 / 24스레드 / 최대 클럭: 5.6GHz / TDP 120W / AMD 라데온 그래픽 / 쿨러 미포함",
  }),
  makeDanawaCpuSample({
    id: "danawa_cpu_amd_ryzen_9_9950x",
    brand: "AMD",
    name: "AMD 라이젠9-6세대 9950X (그래니트 릿지)",
    socket: "AM5",
    generation: "Zen5",
    role: "최신 고성능",
    cores: 16,
    threads: 32,
    boostGhz: 5.7,
    tdpW: 170,
    hasIntegratedGraphics: true,
    coolerIncluded: false,
    rawSpecText:
      "AMD(소켓AM5) / 16코어 / 32스레드 / 최대 클럭: 5.7GHz / TDP 170W / AMD 라데온 그래픽 / 쿨러 미포함",
  }),
];

window.cpuMasterDanawaCpuSamples = {
  collectedAt: "2026-06-04",
  criteria:
    "다나와 CPU 후보 1차 샘플. 인텔 15개, AMD 15개. 잘 팔리는 가성비 모델과 최신형 모델을 혼합했으며, 일부 pcode/가격은 후속 크롤러로 보강 필요.",
  products: danawaCpuSampleProducts,
};
