function makeDanawaRamSample({
  id,
  name,
  brand,
  memoryType,
  capacityGb,
  speedMt,
  modules,
  role,
  sourceProductId,
  productUrl,
  price,
  rawSpecText,
}) {
  const searchUrl = `https://search.danawa.com/dsearch.php?query=${encodeURIComponent(name)}`;
  return {
    id,
    category: "ram",
    name,
    brand,
    memoryType,
    role,
    specs: {
      capacityGb,
      speedMt,
      modules,
      memoryType,
    },
    sourceData: {
      source: "danawa",
      sourceProductId: sourceProductId || `search_${id}`,
      productUrl: productUrl || searchUrl,
      price: price ?? null,
      priceStatus: price ? "samplePrice" : "unknown",
      crawledAt: "2026-06-04",
      rawName: name,
      rawSpecText,
    },
  };
}

function makeDanawaSsdSample({
  id,
  name,
  brand,
  capacityTb,
  readMb,
  writeMb,
  formFactor,
  interfaceType,
  role,
  sourceProductId,
  productUrl,
  price,
  rawSpecText,
}) {
  const searchUrl = `https://search.danawa.com/dsearch.php?query=${encodeURIComponent(name)}`;
  return {
    id,
    category: "ssd",
    name,
    brand,
    role,
    specs: {
      capacityTb,
      capacityGb: capacityTb < 1 ? Math.round(capacityTb * 1000) : capacityTb * 1024,
      readMb,
      writeMb,
      formFactor,
      interfaceType,
    },
    sourceData: {
      source: "danawa",
      sourceProductId: sourceProductId || `search_${id}`,
      productUrl: productUrl || searchUrl,
      price: price ?? null,
      priceStatus: price ? "samplePrice" : "unknown",
      crawledAt: "2026-06-04",
      rawName: name,
      rawSpecText,
    },
  };
}

const danawaRamSampleProducts = [
  makeDanawaRamSample({
    id: "danawa_ram_samsung_ddr4_3200_16gb",
    name: "삼성전자 DDR4-3200 16GB",
    brand: "Samsung",
    memoryType: "DDR4",
    capacityGb: 16,
    speedMt: 3200,
    modules: "16GB x1",
    role: "DDR4 기본 증설",
    rawSpecText:
      "DDR4 / PC4-25600 / 3200MHz / 16GB / 1개 / 데스크탑용 / 기본 메모리 증설용",
  }),
  makeDanawaRamSample({
    id: "danawa_ram_samsung_ddr4_3200_32gb",
    name: "삼성전자 DDR4-3200 32GB",
    brand: "Samsung",
    memoryType: "DDR4",
    capacityGb: 32,
    speedMt: 3200,
    modules: "32GB x1",
    role: "DDR4 대용량 단일",
    rawSpecText:
      "DDR4 / PC4-25600 / 3200MHz / 32GB / 1개 / 데스크탑용 / 대형 파일 작업 증설용",
  }),
  makeDanawaRamSample({
    id: "danawa_ram_teamgroup_ddr4_3200_32gb_kit",
    name: "TeamGroup T-Force DDR4-3200 32GB (16GBx2)",
    brand: "TeamGroup",
    memoryType: "DDR4",
    capacityGb: 32,
    speedMt: 3200,
    modules: "16GB x2",
    role: "DDR4 32GB 균형",
    rawSpecText:
      "DDR4 / PC4-25600 / 3200MHz / 32GB(16GBx2) / 데스크탑용 / 듀얼 채널 구성",
  }),
  makeDanawaRamSample({
    id: "danawa_ram_gskill_ripjaws_v_ddr4_3600_32gb_kit",
    name: "G.SKILL Ripjaws V DDR4-3600 32GB (16GBx2)",
    brand: "G.SKILL",
    memoryType: "DDR4",
    capacityGb: 32,
    speedMt: 3600,
    modules: "16GB x2",
    role: "DDR4 고속 균형",
    rawSpecText:
      "DDR4 / PC4-28800 / 3600MHz / 32GB(16GBx2) / 데스크탑용 / XMP 지원",
  }),
  makeDanawaRamSample({
    id: "danawa_ram_corsair_vengeance_lpx_ddr4_3600_64gb_kit",
    name: "CORSAIR Vengeance LPX DDR4-3600 64GB (32GBx2)",
    brand: "CORSAIR",
    memoryType: "DDR4",
    capacityGb: 64,
    speedMt: 3600,
    modules: "32GB x2",
    role: "DDR4 대용량",
    rawSpecText:
      "DDR4 / PC4-28800 / 3600MHz / 64GB(32GBx2) / 데스크탑용 / 대형 PSD·영상 작업 여유",
  }),
  makeDanawaRamSample({
    id: "danawa_ram_samsung_ddr5_5600_16gb",
    name: "삼성전자 DDR5-5600 16GB",
    brand: "Samsung",
    memoryType: "DDR5",
    capacityGb: 16,
    speedMt: 5600,
    modules: "16GB x1",
    role: "DDR5 기본 증설",
    rawSpecText:
      "DDR5 / PC5-44800 / 5600MHz / 16GB / 1개 / 데스크탑용 / 최신 플랫폼 기본 증설용",
  }),
  makeDanawaRamSample({
    id: "danawa_ram_samsung_ddr5_5600_32gb",
    name: "삼성전자 DDR5-5600 32GB",
    brand: "Samsung",
    memoryType: "DDR5",
    capacityGb: 32,
    speedMt: 5600,
    modules: "32GB x1",
    role: "DDR5 대용량 단일",
    rawSpecText:
      "DDR5 / PC5-44800 / 5600MHz / 32GB / 1개 / 데스크탑용 / 추후 확장 여지",
  }),
  makeDanawaRamSample({
    id: "danawa_ram_skhynix_ddr5_5600_32gb",
    name: "SK하이닉스 DDR5-5600 32GB",
    brand: "SK hynix",
    memoryType: "DDR5",
    capacityGb: 32,
    speedMt: 5600,
    modules: "32GB x1",
    role: "DDR5 대용량 단일",
    rawSpecText:
      "DDR5 / PC5-44800 / 5600MHz / 32GB / 1개 / 데스크탑용 / 최신 플랫폼 작업용",
  }),
  makeDanawaRamSample({
    id: "danawa_ram_gskill_ripjaws_s5_ddr5_6000_32gb_kit",
    name: "G.SKILL Ripjaws S5 DDR5-6000 32GB (16GBx2)",
    brand: "G.SKILL",
    memoryType: "DDR5",
    capacityGb: 32,
    speedMt: 6000,
    modules: "16GB x2",
    role: "DDR5 32GB 균형",
    rawSpecText:
      "DDR5 / PC5-48000 / 6000MHz / 32GB(16GBx2) / 데스크탑용 / EXPO·XMP 지원",
  }),
  makeDanawaRamSample({
    id: "danawa_ram_corsair_vengeance_ddr5_6000_64gb_kit",
    name: "CORSAIR Vengeance DDR5-6000 64GB (32GBx2)",
    brand: "CORSAIR",
    memoryType: "DDR5",
    capacityGb: 64,
    speedMt: 6000,
    modules: "32GB x2",
    role: "DDR5 대용량",
    rawSpecText:
      "DDR5 / PC5-48000 / 6000MHz / 64GB(32GBx2) / 데스크탑용 / 영상·모션·대형 파일 작업 여유",
  }),
];

const danawaSsdSampleProducts = [
  makeDanawaSsdSample({
    id: "danawa_ssd_samsung_980_500gb",
    name: "삼성전자 980 M.2 NVMe 500GB",
    brand: "Samsung",
    capacityTb: 0.5,
    readMb: 3100,
    writeMb: 2600,
    formFactor: "M.2 2280",
    interfaceType: "PCIe 3.0 x4 NVMe",
    role: "500GB 기본형",
    rawSpecText:
      "M.2 2280 / PCIe3.0x4 / NVMe / 500GB / 순차읽기 3100MB/s / 순차쓰기 2600MB/s",
  }),
  makeDanawaSsdSample({
    id: "danawa_ssd_wd_blue_sn580_500gb",
    name: "Western Digital WD Blue SN580 M.2 NVMe 500GB",
    brand: "Western Digital",
    capacityTb: 0.5,
    readMb: 4000,
    writeMb: 3600,
    formFactor: "M.2 2280",
    interfaceType: "PCIe 4.0 x4 NVMe",
    role: "500GB 기본형",
    rawSpecText:
      "M.2 2280 / PCIe4.0x4 / NVMe / 500GB / 순차읽기 4000MB/s / 순차쓰기 3600MB/s",
  }),
  makeDanawaSsdSample({
    id: "danawa_ssd_samsung_990_evo_1tb",
    name: "삼성전자 990 EVO M.2 NVMe 1TB",
    brand: "Samsung",
    capacityTb: 1,
    readMb: 5000,
    writeMb: 4200,
    formFactor: "M.2 2280",
    interfaceType: "PCIe 5.0 x2 / PCIe 4.0 x4 NVMe",
    role: "1TB 균형형",
    rawSpecText:
      "M.2 2280 / PCIe5.0x2·PCIe4.0x4 / NVMe / 1TB / 순차읽기 5000MB/s / 순차쓰기 4200MB/s",
  }),
  makeDanawaSsdSample({
    id: "danawa_ssd_skhynix_platinum_p41_1tb",
    name: "SK하이닉스 Platinum P41 M.2 NVMe 1TB",
    brand: "SK hynix",
    capacityTb: 1,
    readMb: 7000,
    writeMb: 6500,
    formFactor: "M.2 2280",
    interfaceType: "PCIe 4.0 x4 NVMe",
    role: "1TB 고속형",
    rawSpecText:
      "M.2 2280 / PCIe4.0x4 / NVMe / 1TB / 순차읽기 7000MB/s / 순차쓰기 6500MB/s",
  }),
  makeDanawaSsdSample({
    id: "danawa_ssd_samsung_990_pro_2tb",
    name: "삼성전자 990 PRO M.2 NVMe 2TB",
    brand: "Samsung",
    capacityTb: 2,
    readMb: 7450,
    writeMb: 6900,
    formFactor: "M.2 2280",
    interfaceType: "PCIe 4.0 x4 NVMe",
    role: "2TB 고속 작업용",
    rawSpecText:
      "M.2 2280 / PCIe4.0x4 / NVMe / 2TB / 순차읽기 7450MB/s / 순차쓰기 6900MB/s",
  }),
  makeDanawaSsdSample({
    id: "danawa_ssd_wd_black_sn850x_2tb",
    name: "Western Digital WD BLACK SN850X M.2 NVMe 2TB",
    brand: "Western Digital",
    capacityTb: 2,
    readMb: 7300,
    writeMb: 6600,
    formFactor: "M.2 2280",
    interfaceType: "PCIe 4.0 x4 NVMe",
    role: "2TB 고속 작업용",
    rawSpecText:
      "M.2 2280 / PCIe4.0x4 / NVMe / 2TB / 순차읽기 7300MB/s / 순차쓰기 6600MB/s",
  }),
  makeDanawaSsdSample({
    id: "danawa_ssd_crucial_p3_plus_4tb",
    name: "마이크론 Crucial P3 Plus M.2 NVMe 4TB",
    brand: "Crucial",
    capacityTb: 4,
    readMb: 4800,
    writeMb: 4100,
    formFactor: "M.2 2280",
    interfaceType: "PCIe 4.0 x4 NVMe",
    role: "4TB 대용량",
    rawSpecText:
      "M.2 2280 / PCIe4.0x4 / NVMe / 4TB / 순차읽기 4800MB/s / 순차쓰기 4100MB/s",
  }),
  makeDanawaSsdSample({
    id: "danawa_ssd_samsung_990_pro_4tb",
    name: "삼성전자 990 PRO M.2 NVMe 4TB",
    brand: "Samsung",
    capacityTb: 4,
    readMb: 7450,
    writeMb: 6900,
    formFactor: "M.2 2280",
    interfaceType: "PCIe 4.0 x4 NVMe",
    role: "4TB 고속 대용량",
    rawSpecText:
      "M.2 2280 / PCIe4.0x4 / NVMe / 4TB / 순차읽기 7450MB/s / 순차쓰기 6900MB/s",
  }),
  makeDanawaSsdSample({
    id: "danawa_ssd_corsair_mp600_pro_nh_8tb",
    name: "CORSAIR MP600 PRO NH M.2 NVMe 8TB",
    brand: "CORSAIR",
    capacityTb: 8,
    readMb: 7000,
    writeMb: 6100,
    formFactor: "M.2 2280",
    interfaceType: "PCIe 4.0 x4 NVMe",
    role: "8TB 대용량",
    rawSpecText:
      "M.2 2280 / PCIe4.0x4 / NVMe / 8TB / 순차읽기 7000MB/s / 순차쓰기 6100MB/s",
  }),
  makeDanawaSsdSample({
    id: "danawa_ssd_sabrent_rocket_4_plus_8tb",
    name: "Sabrent Rocket 4 Plus M.2 NVMe 8TB",
    brand: "Sabrent",
    capacityTb: 8,
    readMb: 7100,
    writeMb: 6600,
    formFactor: "M.2 2280",
    interfaceType: "PCIe 4.0 x4 NVMe",
    role: "8TB 대용량",
    rawSpecText:
      "M.2 2280 / PCIe4.0x4 / NVMe / 8TB / 순차읽기 7100MB/s / 순차쓰기 6600MB/s",
  }),
];

window.cpuMasterDanawaRamSsdSamples = {
  collectedAt: "2026-06-04",
  criteria: {
    ram: "DDR4 5개, DDR5 5개. 디자인 작업용 16GB~64GB 후보를 우선 배치한 1차 샘플.",
    ssd: "500GB, 1TB, 2TB, 4TB, 8TB 용량 구간별 2개 브랜드씩 배치한 1차 샘플.",
    note: "실시간 가격, 판매 여부, 정확한 다나와 pcode는 후속 크롤링으로 검증 필요.",
  },
  ram: danawaRamSampleProducts,
  ssd: danawaSsdSampleProducts,
  products: {
    ram: danawaRamSampleProducts,
    ssd: danawaSsdSampleProducts,
  },
};
