const programSpecKeyMap = {
  Photoshop: "photoshop",
  Illustrator: "illustrator",
  InDesign: "indesign",
  Figma: "figma",
  "Premiere Pro": "premierePro",
  "After Effects": "afterEffects",
  "DaVinci Resolve": "davinciResolve",
  Blender: "blender",
  "Cinema 4D": "cinema4d",
  "로컬 AI 이미지 생성": "localAiImage",
  "웹 기반 AI 이미지 생성": "webAiImage",
  "웹/레퍼런스 중심 작업": "webReference",
};

const programSpecGuides = {
  photoshop: {
    category: "2D 이미지 편집 / 합성",
    priorityAxes: ["CS", "RAM", "SSD_S", "MON_C", "GPU"],
    officialMinimumGuide: {
      cpu: "멀티코어 Intel/AMD 또는 Apple Silicon 계열 CPU 기준. 실행 자체는 최신 보급형 CPU에서도 가능하지만, 오래된 저전력 CPU는 큰 파일 작업에서 답답할 수 있습니다.",
      ram: "최소 8GB, 권장 16GB 이상 기준.",
      gpu: "DirectX 12 또는 Metal 지원 GPU 기준. 일부 환경에서는 GPU 메모리 4GB 수준이 요구됩니다.",
      vram: "일반 실행 기준에서는 고용량 VRAM이 필수는 아니지만, GPU 가속 기능과 고해상도 화면에서는 VRAM 여유가 필요합니다.",
      storage: "설치 공간과 임시 파일 공간이 필요하며, HDD보다 SSD 사용을 권장합니다.",
      monitor: "기본 해상도에서도 실행은 가능하지만, 실제 디자인 작업에는 FHD 이상이 현실적입니다.",
      note: "공식 기준은 실행 가능 여부에 가깝습니다. 큰 PSD, 다중 레이어, AI 기능, 여러 앱 병행 작업의 체감 기준과는 차이가 있습니다.",
    },
    practicalComfortGuide: {
      cpu: "브러시, 확대·축소, 레이어 전환이 부드럽도록 싱글 성능이 좋은 중급 이상 CPU가 유리합니다.",
      ram: "일반 디자인 작업은 32GB를 현실적인 기준으로 보고, 대형 PSD나 여러 앱을 함께 쓰면 64GB 확장성도 고려하세요.",
      gpu: "중급 GPU면 대부분의 2D 작업에는 충분하며, 일부 필터·AI 기능·고해상도 화면에서 GPU 가속이 도움이 됩니다.",
      vram: "일반 2D 중심이면 8GB 전후로도 충분한 경우가 많고, AI 기능이나 4K/듀얼 모니터를 고려하면 더 여유를 볼 수 있습니다.",
      storage: "빠른 NVMe SSD가 큰 PSD 열기, 저장, 임시 파일 처리에 체감 차이를 만듭니다.",
      monitor: "사진 보정, 합성, 포트폴리오 이미지 확인이 많다면 sRGB 정확도와 선명도가 좋은 IPS/QHD 이상 모니터가 유리합니다.",
      note: "Photoshop은 고급 GPU보다 CPU 반응성, RAM, SSD, 색을 믿을 수 있는 모니터가 더 크게 체감될 수 있습니다.",
    },
    overkillWarning:
      "Photoshop 중심 작업만 한다면 최고급 RTX 그래픽카드보다 RAM, SSD, CPU 반응성, 모니터 색 정확도에 예산을 두는 편이 더 효율적일 수 있습니다.",
    designerExplanation: {
      CS: "브러시 반응, 확대·축소, 레이어 전환처럼 계속 반복되는 조작감에 영향을 줍니다.",
      RAM: "큰 PSD와 여러 레이어를 동시에 다룰 때 작업 여유를 만들어줍니다.",
      SSD_S: "큰 파일을 열고 저장하거나 임시 파일을 처리할 때 답답함을 줄여줍니다.",
      MON_C: "색 보정과 합성 결과를 믿고 판단하려면 모니터 색 정확도와 선명도가 중요합니다.",
      GPU: "일부 필터, 화면 표시, AI 기능에서 도움을 주지만 모든 예산을 GPU에 몰 필요는 낮습니다.",
    },
    sourceNote: "초기 mock 데이터. Adobe 공식 시스템 요구사항과 실제 디자인 작업용 벤치마크로 추가 검증 필요.",
  },
  illustrator: {
    category: "벡터 그래픽 / 로고 / 편집용 아트워크",
    priorityAxes: ["CS", "RAM", "MON_C", "MON_S", "SSD_S"],
    officialMinimumGuide: {
      cpu: "64비트 지원 Intel/AMD 또는 Apple Silicon 계열 CPU 기준. 기본 실행은 가능하지만 복잡한 벡터 오브젝트에서는 CPU 반응성이 중요합니다.",
      ram: "공식 기준은 비교적 낮은 RAM에서도 실행 가능하지만, 실무 파일에는 더 큰 여유가 필요합니다.",
      gpu: "GPU Performance 기능을 쓰려면 Windows 기준 최소 1GB VRAM, 4GB VRAM 권장.",
      vram: "일반 벡터 작업에서는 고용량 VRAM이 핵심은 아니지만, GPU Performance와 복잡한 화면 표시에는 일정 VRAM이 필요합니다.",
      storage: "프로그램 설치와 작업 파일 저장을 위한 SSD 권장.",
      monitor: "최소 1024×768, 권장 1920×1080 이상. Scalable UI 사용에는 FHD급 해상도가 사실상 필요합니다.",
      note: "공식 기준은 실행과 GPU Performance 기준에 가깝습니다. 다중 아트보드, 복잡한 패스, 링크 이미지 작업은 더 높은 체감 사양이 필요할 수 있습니다.",
    },
    practicalComfortGuide: {
      cpu: "오브젝트가 많은 파일을 부드럽게 다루려면 싱글 성능이 안정적인 CPU가 유리합니다.",
      ram: "여러 아트보드, 링크 이미지, 복잡한 벡터 파일을 다룬다면 16GB보다 32GB 구성이 안정적입니다.",
      gpu: "고급 GPU보다는 기본적인 GPU 가속을 안정적으로 지원하는 정도면 충분한 경우가 많습니다.",
      vram: "2D 벡터 중심이라면 고용량 VRAM보다 RAM과 CPU 반응성을 우선하세요.",
      storage: "작업 파일과 링크 이미지를 빠르게 불러오기 위해 NVMe SSD가 유리합니다.",
      monitor: "얇은 선, 타이포, 색상 확인이 중요하므로 QHD급 이상 선명도와 색 재현이 좋은 모니터가 도움이 됩니다.",
      note: "Illustrator는 그래픽카드 등급보다 복잡한 벡터를 다룰 때의 CPU 반응성, RAM, 모니터 선명도가 더 크게 체감될 수 있습니다.",
    },
    overkillWarning: "Illustrator 중심 작업에서는 최고급 GPU보다 CPU 반응성, RAM, 선명한 모니터가 더 중요할 수 있습니다.",
    designerExplanation: {
      CS: "패스가 많은 오브젝트를 선택하고 이동할 때의 즉각적인 반응성에 영향을 줍니다.",
      RAM: "여러 아트보드와 링크 이미지를 함께 다룰 때 작업 여유를 만듭니다.",
      MON_C: "선, 글자, 색상 차이를 정확히 확인하는 데 중요합니다.",
      MON_S: "여러 아트보드와 패널을 넓게 펼쳐두는 작업에 도움이 됩니다.",
      SSD_S: "링크 이미지와 작업 파일을 빠르게 불러오는 데 영향을 줍니다.",
    },
    sourceNote: "초기 mock 데이터. Adobe 공식 시스템 요구사항과 실제 벡터 작업 벤치마크로 추가 검증 필요.",
  },
  indesign: {
    category: "편집 디자인 / 출판 / 다중 페이지 문서",
    priorityAxes: ["RAM", "CS", "MON_C", "MON_S", "SSD_S"],
    officialMinimumGuide: {
      cpu: "64비트 지원 Intel/AMD 또는 Apple Silicon 계열 CPU 기준. 긴 문서 작업에서는 기본 실행보다 반응성이 중요합니다.",
      ram: "공식 실행 기준은 낮은 RAM에서도 가능하지만, 여러 페이지와 이미지 링크가 많으면 부족할 수 있습니다.",
      gpu: "GPU Performance 사용 시 Windows 기준 최소 1024MB VRAM, 2GB VRAM 권장.",
      vram: "GPU Performance와 2K 이상 모니터 환경에서는 최소 1GB 이상, 권장 2GB 수준의 VRAM이 필요합니다.",
      storage: "설치 공간과 문서/링크 이미지 저장 공간이 필요하며 SSD 권장.",
      monitor: "Scalable UI에는 최소 1920×1080 해상도가 요구되며, Touch workspace는 더 높은 해상도 조건이 필요합니다.",
      note: "공식 기준은 실행 및 GPU Performance 기준입니다. 책자, 잡지, 이미지 많은 긴 문서는 더 많은 RAM과 저장장치 체감이 필요할 수 있습니다.",
    },
    practicalComfortGuide: {
      cpu: "페이지 이동, 이미지 링크 처리, PDF 내보내기가 답답하지 않도록 안정적인 중급 CPU가 유리합니다.",
      ram: "긴 문서, 이미지 많은 편집물, 여러 파일 동시 작업이 있다면 32GB 구성을 권장합니다.",
      gpu: "고급 GPU는 필수는 아니지만, 고해상도 모니터와 GPU Performance 기능을 고려하면 기본 VRAM 여유는 필요합니다.",
      vram: "일반 편집 디자인은 2GB 이상 기준으로 충분한 경우가 많고, 고해상도 모니터나 여러 화면에서는 더 여유를 볼 수 있습니다.",
      storage: "링크 이미지, PDF, 패키징 파일을 빠르게 다루려면 NVMe SSD가 유리합니다.",
      monitor: "페이지 전체와 세부 타이포를 함께 보려면 QHD 이상 해상도와 색 재현이 좋은 모니터가 도움이 됩니다.",
      note: "InDesign은 GPU보다 RAM, 저장장치, 모니터 작업 공간과 선명도가 작업 효율에 더 직접적으로 연결됩니다.",
    },
    overkillWarning: "InDesign 중심 작업에서 최고급 그래픽카드는 과할 수 있습니다. 긴 문서 안정성, RAM, SSD, 모니터 품질을 먼저 보세요.",
    designerExplanation: {
      RAM: "여러 페이지, 링크 이미지, 긴 문서를 안정적으로 유지하는 데 중요합니다.",
      CS: "페이지 이동, 오브젝트 편집, 패널 조작의 반응성에 영향을 줍니다.",
      MON_C: "타이포와 인쇄 색상 확인에 중요합니다.",
      MON_S: "페이지, 패널, 원고, 참고 자료를 함께 펼쳐두는 데 도움이 됩니다.",
      SSD_S: "링크 이미지와 PDF 내보내기, 패키징 과정에서 체감될 수 있습니다.",
    },
    sourceNote: "초기 mock 데이터. Adobe 공식 시스템 요구사항과 실제 편집 문서 작업 기준으로 추가 검증 필요.",
  },
  figma: {
    category: "UI/UX 디자인 / 브라우저 기반 협업 작업",
    priorityAxes: ["RAM", "CS", "MON_S", "MON_C", "SSD_S"],
    officialMinimumGuide: {
      cpu: "Figma는 브라우저 기반이므로 특정 고성능 CPU보다 지원 브라우저와 WebGL 환경이 중요합니다.",
      ram: "공식 문서가 특정 RAM 용량을 강하게 요구하지는 않지만, 브라우저 탭과 파일 수가 많으면 RAM 사용량이 커질 수 있습니다.",
      gpu: "WebGL 1.0 최소, WebGL 2.0 또는 WebGPU 권장. 대부분의 최신 내장 그래픽으로도 실행 가능합니다.",
      vram: "일반 Figma 작업에서는 고용량 VRAM이 핵심 요구사항은 아닙니다.",
      storage: "로컬 저장공간 요구는 낮지만, 브라우저 캐시와 다운로드 파일을 위한 SSD 여유가 있으면 좋습니다.",
      monitor: "기본 모니터에서도 실행은 가능하지만, UI 디테일 확인과 다중 프레임 작업에는 선명도와 화면 공간이 중요합니다.",
      note: "공식 기준은 브라우저/WebGL 지원 중심입니다. 실제 작업에서는 브라우저 탭 수, 파일 복잡도, 모니터 작업 공간이 체감에 더 큽니다.",
    },
    practicalComfortGuide: {
      cpu: "컴포넌트가 많은 파일과 브라우저 탭을 부드럽게 다루려면 최신 중급 CPU의 체감 성능이 유리합니다.",
      ram: "Figma, 브라우저, 레퍼런스, 메신저를 함께 쓴다면 16GB보다 32GB 구성이 안정적입니다.",
      gpu: "대부분의 Figma 작업은 고급 GPU가 필요하지 않으며, 최신 내장 그래픽이나 보급형 GPU로도 충분한 경우가 많습니다.",
      vram: "VRAM보다 브라우저 안정성, RAM, 화면 공간이 더 중요합니다.",
      storage: "SSD는 프로그램 실행보다 브라우저 캐시, 다운로드 자료, 레퍼런스 관리에서 체감될 수 있습니다.",
      monitor: "프레임, 컴포넌트, 피드백 창을 함께 보려면 27인치 QHD 이상이나 듀얼 모니터가 유리합니다.",
      note: "Figma는 고급 그래픽카드보다 RAM, 브라우저 반응성, 넓고 선명한 화면이 더 중요합니다.",
    },
    overkillWarning: "Figma 중심 작업만 한다면 고성능 GPU보다 RAM, CPU 체감 성능, 넓은 모니터에 예산을 쓰는 편이 효율적입니다.",
    designerExplanation: {
      RAM: "브라우저 탭, Figma 파일, 레퍼런스 자료를 동시에 열어둘 때 안정성에 영향을 줍니다.",
      CS: "파일 안에서 프레임을 이동하고 컴포넌트를 편집할 때의 반응성에 영향을 줍니다.",
      MON_S: "여러 프레임과 피드백 문서를 한 화면에 펼쳐두는 데 중요합니다.",
      MON_C: "작은 글자, 간격, UI 색상을 확인할 때 선명도와 색 재현이 필요합니다.",
      SSD_S: "브라우저 캐시와 다운로드 자료 관리에서 간접적인 체감이 있습니다.",
    },
    sourceNote: "초기 mock 데이터. Figma 공식 시스템 요구사항과 실제 브라우저 기반 대형 파일 사용 사례로 추가 검증 필요.",
  },
  premierePro: {
    category: "영상 편집 / 인코딩 / 타임라인 작업",
    priorityAxes: ["CM", "RAM", "SSD_S", "SSD_C", "GPU", "VRAM", "COOL"],
    officialMinimumGuide: {
      cpu: "최신 멀티코어 CPU 기준. 영상 코덱과 해상도에 따라 CPU 부담이 커질 수 있습니다.",
      ram: "최소 8GB, HD 미디어 권장 16GB, 4K 이상은 32GB 이상 권장.",
      gpu: "NVIDIA Maxwell 세대 이상 또는 Intel/AMD GPU 기준으로 최소 4GB GPU 메모리 필요.",
      vram: "최소 4GB GPU 메모리, 권장 기준에서는 8GB GPU 메모리가 제시됩니다.",
      storage: "설치 공간 외에 미디어 파일, 캐시, 프리뷰 파일을 위한 빠른 저장장치가 필요합니다.",
      monitor: "기본 편집은 일반 모니터에서도 가능하지만, 영상 색 확인에는 해상도와 색 재현이 중요합니다.",
      note: "공식 기준은 해상도별 RAM과 GPU 메모리 요구를 구분합니다. 실제 작업에서는 코덱, 효과, 원본 해상도, 캐시 드라이브가 큰 차이를 만듭니다.",
    },
    practicalComfortGuide: {
      cpu: "4K 편집과 인코딩을 고려하면 코어 수와 멀티 성능이 좋은 중급 이상 CPU가 유리합니다.",
      ram: "FHD 중심은 16GB도 가능하지만, 4K·멀티캠·여러 앱 병행이면 32GB 이상이 현실적입니다.",
      gpu: "색보정, 효과, GPU 가속을 고려하면 중급 이상 GPU가 유리하지만 최상급 GPU가 항상 필요한 것은 아닙니다.",
      vram: "4K 이상, 효과 많은 타임라인, 고해상도 모니터를 고려하면 8GB 이상 VRAM을 우선 확인하세요.",
      storage: "원본 영상, 프록시, 캐시, 내보내기 파일을 위해 빠른 NVMe SSD와 충분한 용량이 중요합니다.",
      monitor: "영상 확인용으로는 QHD 이상 작업 공간과 색 재현이 안정적인 모니터가 도움이 됩니다.",
      note: "Premiere Pro는 CPU 멀티, RAM, SSD, GPU 가속이 균형 있게 필요합니다. 한 부품만 올린다고 전체 문제가 해결되지는 않습니다.",
    },
    overkillWarning: "간단한 FHD 컷 편집 중심이라면 최고급 GPU보다 RAM 32GB, 빠른 SSD, 적절한 CPU가 더 먼저 체감될 수 있습니다.",
    designerExplanation: {
      CM: "인코딩, 렌더링, 미리보기 생성처럼 오래 걸리는 작업 시간을 줄이는 데 중요합니다.",
      RAM: "긴 타임라인과 여러 소스를 안정적으로 다루는 데 필요합니다.",
      SSD_S: "원본 영상 읽기, 캐시, 프리뷰 파일 생성 속도에 영향을 줍니다.",
      SSD_C: "영상 원본과 내보내기 파일은 빠르게 쌓이므로 용량 여유가 중요합니다.",
      GPU: "효과, 색보정, 일부 프리뷰와 하드웨어 가속에 도움을 줍니다.",
      VRAM: "4K 이상 미디어와 효과 많은 타임라인에서 그래픽 메모리 부족을 줄여줍니다.",
      COOL: "긴 인코딩 중 발열과 소음, 성능 저하를 막는 데 중요합니다.",
    },
    sourceNote: "초기 mock 데이터. Adobe 공식 시스템 요구사항과 Premiere Pro 실제 코덱/해상도별 벤치마크로 추가 검증 필요.",
  },
  afterEffects: {
    category: "모션그래픽 / 합성 / RAM 프리뷰",
    priorityAxes: ["RAM", "CM", "SSD_S", "GPU", "VRAM", "COOL", "CS"],
    officialMinimumGuide: {
      cpu: "멀티코어 CPU 기준. 합성, 이펙트, 렌더링에서 CPU 성능 영향을 받습니다.",
      ram: "최소 16GB 수준, 권장 32GB 이상 기준으로 보는 것이 안전합니다.",
      gpu: "일부 환경에서 4GB GPU 메모리 기준이 제시되며, GPU 가속 효과 사용 시 그래픽 성능이 필요합니다.",
      vram: "GPU 가속 효과와 고해상도 컴포지션에서는 VRAM 여유가 도움이 됩니다.",
      storage: "설치 공간 외에 디스크 캐시를 위한 빠르고 여유 있는 SSD가 중요합니다.",
      monitor: "기본 모니터에서도 작업은 가능하지만, 타임라인·프리뷰·패널을 함께 쓰기 위해 작업 공간이 중요합니다.",
      note: "공식 기준은 실행 가능 기준에 가깝습니다. After Effects는 실제 작업에서 RAM과 디스크 캐시 체감이 매우 큽니다.",
    },
    practicalComfortGuide: {
      cpu: "렌더링과 프리뷰 생성을 고려하면 멀티 성능이 좋은 중급 이상 CPU가 유리합니다.",
      ram: "모션그래픽과 합성 작업은 32GB를 현실적인 기준으로 보고, 복잡한 컴포지션은 64GB 이상도 고려하세요.",
      gpu: "GPU 가속 효과와 3D 레이어를 쓰면 중급 GPU가 도움이 되지만, 모든 병목이 GPU에서 생기지는 않습니다.",
      vram: "고해상도 컴포지션, GPU 가속 효과, 3D 관련 작업을 고려하면 8GB 이상 VRAM이 안정적입니다.",
      storage: "디스크 캐시용 빠른 NVMe SSD를 확보하면 프리뷰와 작업 반복에서 체감 차이가 큽니다.",
      monitor: "타임라인, 컴포지션, 효과 패널을 함께 보려면 QHD 이상 또는 듀얼 모니터가 유리합니다.",
      note: "After Effects는 GPU보다 RAM과 SSD 캐시가 더 먼저 병목이 되는 경우가 많습니다.",
    },
    overkillWarning: "After Effects를 쓴다고 무조건 최고급 GPU가 필요한 것은 아닙니다. RAM, SSD 캐시, CPU 멀티 성능을 먼저 확인하세요.",
    designerExplanation: {
      RAM: "RAM 프리뷰와 여러 컴포지션을 유지하는 데 직접적으로 영향을 줍니다.",
      CM: "렌더링과 프리뷰 생성 시간을 줄이는 데 중요합니다.",
      SSD_S: "디스크 캐시가 빠를수록 프리뷰 반복 작업이 덜 답답합니다.",
      GPU: "일부 효과와 3D 관련 기능에서 가속을 제공합니다.",
      VRAM: "고해상도 컴포지션과 GPU 가속 효과에서 여유를 만들어줍니다.",
      COOL: "긴 렌더링 중 발열과 소음, 성능 저하를 줄이는 데 필요합니다.",
      CS: "타임라인 조작과 일반 UI 반응성에도 일정 영향을 줍니다.",
    },
    sourceNote: "초기 mock 데이터. Adobe 공식 시스템 요구사항과 After Effects 실사용 벤치마크로 추가 검증 필요.",
  },
  davinciResolve: {
    category: "영상 편집 / 색보정 / 노드 기반 후반 작업",
    priorityAxes: ["GPU", "VRAM", "RAM", "SSD_S", "SSD_C", "CM", "MON_C", "COOL"],
    officialMinimumGuide: {
      cpu: "최신 멀티코어 CPU 기준. 디코딩, 인코딩, Fusion 작업에서 CPU 부담이 생길 수 있습니다.",
      ram: "일반적으로 16GB 이상이 최소선으로 언급되며, Fusion이나 무거운 작업은 32GB 이상이 필요할 수 있습니다.",
      gpu: "OpenCL 또는 CUDA를 지원하는 통합/외장 GPU 기준. 실제 작업에서는 외장 GPU가 유리합니다.",
      vram: "최소 2GB~4GB VRAM 수준이 언급되지만, 고해상도 색보정과 Fusion 작업에는 더 큰 VRAM이 필요합니다.",
      storage: "영상 원본과 캐시를 위한 빠른 SSD가 필요합니다.",
      monitor: "색보정 작업에서는 색 정확도와 해상도가 중요합니다.",
      note: "공식·배포 문서 기준의 최소선은 기본 실행 기준에 가깝습니다. Resolve는 실제 작업에서 GPU와 VRAM 영향이 매우 큽니다.",
    },
    practicalComfortGuide: {
      cpu: "4K 영상과 인코딩을 고려하면 멀티 성능이 좋은 중급 이상 CPU가 유리합니다.",
      ram: "4K 편집과 Fusion 가능성을 고려하면 32GB 이상을 현실적인 기준으로 보고, 복잡한 작업은 64GB도 고려하세요.",
      gpu: "Resolve는 GPU 의존도가 높으므로 중급 이상 외장 GPU가 유리합니다.",
      vram: "4K 색보정, 노드, NR, Fusion 작업을 고려하면 8GB 이상, 여유 있게는 12GB 이상 VRAM을 확인하세요.",
      storage: "원본 영상, 캐시, 프록시, 내보내기 파일을 위해 빠른 NVMe SSD와 1TB 이상 용량이 유리합니다.",
      monitor: "색보정 중심이라면 색역, 색 정확도, 밝기, 캘리브레이션 가능성을 우선 확인하세요.",
      note: "DaVinci Resolve는 2D 디자인 프로그램보다 GPU와 VRAM 우선순위가 훨씬 높게 잡히는 편입니다.",
    },
    overkillWarning: "단순 컷 편집만 한다면 최고급 GPU까지는 과할 수 있지만, 색보정·Fusion·노이즈 제거를 쓴다면 GPU와 VRAM을 낮게 잡으면 바로 한계가 올 수 있습니다.",
    designerExplanation: {
      GPU: "색보정, 효과, 노드 처리, 실시간 프리뷰에서 큰 비중을 차지합니다.",
      VRAM: "고해상도 영상과 복잡한 노드 작업에서 작업 안정성을 좌우할 수 있습니다.",
      RAM: "긴 프로젝트와 Fusion 작업을 안정적으로 유지하는 데 필요합니다.",
      SSD_S: "영상 원본 읽기, 캐시, 프록시 작업 속도에 영향을 줍니다.",
      SSD_C: "영상 원본과 캐시 파일은 빠르게 쌓이므로 용량 여유가 중요합니다.",
      CM: "인코딩과 일부 처리 과정에서 시간을 줄이는 데 도움이 됩니다.",
      MON_C: "색보정 결과를 믿고 판단하려면 모니터 색 정확도가 중요합니다.",
      COOL: "GPU 부하가 긴 작업에서 발열과 소음 관리를 필요로 합니다.",
    },
    sourceNote: "초기 mock 데이터. Blackmagic Design 자료와 Resolve 버전별 공식 가이드, 실제 색보정/코덱 벤치마크로 추가 검증 필요.",
  },
  blender: {
    category: "3D 모델링 / 렌더링 / 애니메이션",
    priorityAxes: ["GPU", "VRAM", "RAM", "CS", "CM", "SSD_C", "COOL", "MON_S"],
    officialMinimumGuide: {
      cpu: "최소 4코어 CPU와 SSE4.2 지원 기준.",
      ram: "최소 8GB RAM 기준.",
      gpu: "최소 2GB VRAM, OpenGL 4.3 및 Vulkan 1.3 지원 GPU 기준.",
      vram: "최소 2GB VRAM 기준. 단, 복잡한 장면과 렌더링에는 부족할 수 있습니다.",
      storage: "프로그램 설치와 프로젝트 파일 저장 공간이 필요하며, SSD 사용을 권장합니다.",
      monitor: "기본 모니터에서도 실행 가능하지만, 3D 뷰포트와 패널을 함께 쓰려면 넓은 작업 공간이 유리합니다.",
      note: "공식 최소는 Blender 실행과 간단한 작업 기준입니다. 렌더링, 고해상도 텍스처, 복잡한 장면은 훨씬 높은 사양을 요구할 수 있습니다.",
    },
    practicalComfortGuide: {
      cpu: "모델링 조작감과 일부 시뮬레이션을 고려하면 싱글 성능이 좋은 중급 이상 CPU가 유리합니다.",
      ram: "간단한 학습은 16GB도 가능하지만, 실제 장면 작업은 32GB 이상을 권장하고 큰 프로젝트는 64GB도 고려하세요.",
      gpu: "Cycles GPU 렌더링과 뷰포트 작업을 고려하면 NVIDIA RTX급 또는 동급 이상의 외장 GPU가 유리합니다.",
      vram: "복잡한 장면, 고해상도 텍스처, GPU 렌더링을 고려하면 8GB 이상, 여유 있게는 12GB 이상 VRAM을 확인하세요.",
      storage: "프로젝트 파일, 텍스처, 캐시가 쌓이므로 1TB 이상 SSD와 추가 저장장치 확장성을 고려하세요.",
      monitor: "3D 뷰포트, 노드, 타임라인, 레퍼런스를 함께 보기 위해 QHD 이상 또는 듀얼 모니터가 유리합니다.",
      note: "Blender는 2D 프로그램보다 GPU, VRAM, 쿨링·파워의 중요도가 크게 올라갑니다.",
    },
    overkillWarning: "간단한 모델링 학습만 한다면 최고급 GPU는 과할 수 있지만, GPU 렌더링과 복잡한 장면을 목표로 한다면 VRAM을 너무 낮게 잡지 않는 것이 중요합니다.",
    designerExplanation: {
      GPU: "뷰포트 표시와 GPU 렌더링 속도에 직접적으로 영향을 줍니다.",
      VRAM: "장면, 텍스처, 렌더링 데이터를 그래픽카드 안에 담는 여유를 만듭니다.",
      RAM: "장면 데이터와 여러 앱 병행 작업을 안정적으로 유지하는 데 필요합니다.",
      CS: "모델링 중 선택, 이동, 회전 같은 조작감에 영향을 줍니다.",
      CM: "CPU 렌더링이나 일부 시뮬레이션 작업에서 도움이 됩니다.",
      SSD_C: "텍스처, 캐시, 프로젝트 파일이 빠르게 쌓이므로 저장공간 확장성이 중요합니다.",
      COOL: "긴 렌더링 중 발열과 소음을 관리하는 데 필요합니다.",
      MON_S: "뷰포트, 노드, 레퍼런스를 함께 보는 작업 공간에 영향을 줍니다.",
    },
    sourceNote: "초기 mock 데이터. Blender 공식 요구사항과 Cycles/Eevee 렌더링 벤치마크로 추가 검증 필요.",
  },
  cinema4d: {
    category: "3D 모션그래픽 / 모델링 / 렌더링",
    priorityAxes: ["GPU", "VRAM", "RAM", "CS", "CM", "SSD_C", "COOL", "MON_S"],
    officialMinimumGuide: {
      cpu: "최신 64비트 Intel/AMD 또는 Apple Silicon 계열 CPU 기준.",
      ram: "통합 GPU 시스템은 16GB 이상 RAM 권장. 기본 실행에는 더 낮은 RAM도 가능하지만 실사용에는 부족할 수 있습니다.",
      gpu: "DirectX 12 Feature Level 11.0 지원 GPU 기준. 전용 AMD/NVIDIA 3D 그래픽카드 권장.",
      vram: "전용 3D 그래픽카드는 최소 4GB VRAM, 8GB 이상 권장.",
      storage: "프로그램 설치와 프로젝트 파일, 텍스처, 캐시 저장 공간 필요.",
      monitor: "기본 모니터에서도 실행 가능하지만, 3D 작업에는 넓은 화면과 선명도가 유리합니다.",
      note: "공식 기준은 Cinema 4D 실행과 그래픽 호환성 기준입니다. Redshift 렌더링을 고려하면 GPU와 VRAM 기준을 더 높게 봐야 합니다.",
    },
    practicalComfortGuide: {
      cpu: "모션그래픽 작업과 뷰포트 조작을 고려하면 싱글 성능이 좋은 중급 이상 CPU가 유리합니다.",
      ram: "실제 3D 모션 작업은 32GB 이상을 권장하고, 복잡한 장면이나 다른 Adobe 앱 병행 시 64GB도 고려하세요.",
      gpu: "Redshift나 GPU 렌더링을 고려한다면 중급 이상 외장 GPU가 사실상 중요합니다.",
      vram: "복잡한 장면, 텍스처, 렌더링을 고려하면 8GB 이상, 여유 있게는 12GB 이상 VRAM을 확인하세요.",
      storage: "텍스처, 캐시, 렌더 결과물이 쌓이므로 1TB 이상 SSD와 추가 저장장치 확장성이 유리합니다.",
      monitor: "타임라인, 뷰포트, 오브젝트 매니저, 레퍼런스를 함께 보기 위해 QHD 이상 화면이 도움이 됩니다.",
      note: "Cinema 4D는 GPU 렌더러 사용 여부에 따라 필요한 그래픽카드 등급이 크게 달라집니다.",
    },
    overkillWarning: "간단한 3D 학습이나 가벼운 모션그래픽만 한다면 최고급 GPU가 필수는 아닙니다. 하지만 Redshift와 복잡한 장면을 쓴다면 VRAM과 쿨링을 낮게 잡으면 한계가 빨리 옵니다.",
    designerExplanation: {
      GPU: "뷰포트와 GPU 렌더링 작업 속도에 큰 영향을 줍니다.",
      VRAM: "텍스처와 복잡한 장면을 그래픽카드에서 처리할 여유를 만듭니다.",
      RAM: "장면 데이터와 다른 디자인 툴 병행 작업을 안정적으로 유지합니다.",
      CS: "오브젝트 조작, 타임라인 이동, 뷰포트 반응성에 영향을 줍니다.",
      CM: "CPU 렌더링이나 일부 계산 작업에서 도움이 됩니다.",
      SSD_C: "텍스처, 캐시, 렌더 결과물이 쌓이므로 저장공간 여유가 중요합니다.",
      COOL: "긴 렌더링 중 발열과 소음을 관리합니다.",
      MON_S: "뷰포트와 패널을 넓게 펼쳐두는 작업 공간에 영향을 줍니다.",
    },
    sourceNote: "초기 mock 데이터. Maxon 공식 시스템 요구사항과 Redshift/Cinema 4D 실사용 벤치마크로 추가 검증 필요.",
  },
  localAiImage: {
    category: "로컬 AI 이미지 생성 / Stable Diffusion / ComfyUI",
    priorityAxes: ["VRAM", "GPU", "RAM", "SSD_C", "SSD_S", "COOL"],
    officialMinimumGuide: {
      cpu: "CPU만으로도 일부 실행은 가능하지만, 이미지 생성 속도가 매우 느릴 수 있습니다.",
      ram: "도구에 따라 8GB~16GB 수준에서도 실행 가능하지만, 모델과 워크플로가 커지면 부족할 수 있습니다.",
      gpu: "ComfyUI 등 로컬 생성 환경은 NVIDIA GPU와 CUDA 환경이 가장 일반적이며, 기본 실행에는 4GB VRAM 수준도 언급됩니다.",
      vram: "기본 모델은 4GB~8GB VRAM에서도 최적화로 실행 가능하지만, SDXL·Flux·ControlNet·고해상도 작업은 더 큰 VRAM이 필요합니다.",
      storage: "모델, LoRA, 체크포인트, 결과물이 쌓이므로 최소 수십 GB 이상 여유가 필요합니다.",
      monitor: "생성 결과 비교와 후작업을 위해 색과 선명도가 안정적인 모니터가 도움이 됩니다.",
      note: "로컬 AI는 사용하는 모델과 워크플로에 따라 요구 사양 차이가 매우 큽니다. 공식 최소선은 기본 실행 가능성에 가깝습니다.",
    },
    practicalComfortGuide: {
      cpu: "이미지 생성 자체는 GPU 영향이 크지만, 파일 관리와 다른 앱 병행을 위해 최신 중급 CPU가 유리합니다.",
      ram: "여러 모델과 브라우저, 후작업 툴을 함께 쓴다면 32GB 이상을 권장합니다.",
      gpu: "생성 속도와 호환성을 고려하면 NVIDIA RTX 계열 GPU가 가장 무난합니다.",
      vram: "SDXL이나 복잡한 ComfyUI 워크플로를 고려하면 12GB 이상, 큰 모델과 고해상도 작업은 16GB 이상을 우선 확인하세요.",
      storage: "체크포인트, LoRA, ControlNet, 결과물이 빠르게 쌓이므로 1TB 이상 SSD와 추가 저장공간을 권장합니다.",
      monitor: "결과물 선별과 보정까지 고려하면 색과 선명도가 안정적인 모니터가 좋습니다.",
      note: "로컬 AI는 GPU 칩셋 성능만큼 VRAM 용량이 중요합니다. VRAM이 부족하면 속도보다 실행 가능 여부가 먼저 문제가 될 수 있습니다.",
    },
    overkillWarning: "웹 기반 AI만 쓴다면 고급 RTX GPU는 거의 필요하지 않습니다. 로컬 생성, 큰 모델, ControlNet, 고해상도 워크플로를 실제로 쓸 때만 VRAM 중심 GPU 투자가 의미 있습니다.",
    designerExplanation: {
      VRAM: "모델과 생성 데이터를 그래픽카드 안에 올리는 공간입니다. 부족하면 실행이 제한되거나 매우 느려질 수 있습니다.",
      GPU: "이미지 생성 속도와 GPU 가속 처리에 직접적으로 영향을 줍니다.",
      RAM: "여러 모델, 브라우저, 후작업 앱을 함께 사용할 때 안정성을 만듭니다.",
      SSD_C: "모델 파일과 결과물이 빠르게 쌓이므로 저장공간이 중요합니다.",
      SSD_S: "모델 로딩과 파일 불러오기 속도에 영향을 줍니다.",
      COOL: "장시간 생성 작업 중 발열과 소음을 관리하는 데 필요합니다.",
    },
    sourceNote: "초기 mock 데이터. ComfyUI 공식 문서, Stability AI 모델 정보, PyTorch/CUDA 환경 기준으로 추가 검증 필요.",
  },
  webAiImage: {
    category: "웹 기반 AI 이미지 생성 / Firefly / Midjourney 등",
    priorityAxes: ["RAM", "CS", "MON_C", "MON_S", "SSD_C"],
    officialMinimumGuide: {
      cpu: "웹 브라우저가 안정적으로 동작할 수 있는 최신 CPU 기준.",
      ram: "브라우저 탭과 이미지 결과물을 여러 개 열어두려면 기본 RAM 여유가 필요합니다.",
      gpu: "이미지 생성 자체는 서버에서 처리되므로 로컬 고성능 GPU가 필수는 아닙니다.",
      vram: "웹 기반 AI만 사용한다면 고용량 VRAM은 핵심 조건이 아닙니다.",
      storage: "다운로드한 결과물과 레퍼런스 이미지를 저장할 공간이 필요합니다.",
      monitor: "생성 결과를 비교하고 후작업할 수 있는 선명한 화면이 유리합니다.",
      note: "웹 기반 AI는 PC 내부 GPU보다 브라우저 안정성, 인터넷 환경, 모니터 확인 환경이 더 중요합니다.",
    },
    practicalComfortGuide: {
      cpu: "브라우저와 디자인 툴을 함께 쓰기 위해 최신 보급형~중급 CPU면 충분한 경우가 많습니다.",
      ram: "여러 AI 결과물, 레퍼런스, 디자인 툴을 함께 열면 16GB보다 32GB가 더 안정적입니다.",
      gpu: "웹 AI 중심이면 고급 GPU보다 기본적인 화면 출력과 브라우저 가속이 안정적인 정도면 충분합니다.",
      vram: "로컬 AI를 돌리지 않는다면 VRAM에 큰 예산을 둘 필요는 낮습니다.",
      storage: "결과물, 프롬프트 자료, 레퍼런스 이미지를 관리하기 위해 1TB 정도의 SSD 여유가 있으면 좋습니다.",
      monitor: "결과물 비교와 후보 선별을 위해 색과 선명도가 안정적인 모니터가 도움이 됩니다.",
      note: "웹 기반 AI는 생성 성능보다 결과물을 확인하고 정리하고 후작업하는 환경이 더 중요합니다.",
    },
    overkillWarning: "Midjourney, Firefly처럼 웹에서 생성하는 AI만 쓴다면 RTX 고급 GPU는 거의 필요하지 않습니다. RAM, 모니터, 저장공간에 예산을 두는 편이 더 실용적입니다.",
    designerExplanation: {
      RAM: "브라우저 탭, 생성 결과, 디자인 툴을 함께 열어둘 때 안정성에 영향을 줍니다.",
      CS: "브라우저와 후작업 툴을 오갈 때의 반응성에 영향을 줍니다.",
      MON_C: "생성 결과의 색과 디테일을 비교하고 선별하는 데 중요합니다.",
      MON_S: "여러 결과물과 레퍼런스를 한 화면에 펼쳐두는 데 도움이 됩니다.",
      SSD_C: "다운로드한 결과물과 레퍼런스 파일이 쌓일 때 저장공간 여유를 만듭니다.",
    },
    sourceNote: "초기 mock 데이터. 각 웹 AI 서비스의 공식 권장 환경과 브라우저 요구사항으로 추가 검증 필요.",
  },
  webReference: {
    category: "웹 리서치 / 레퍼런스 수집 / 자료 정리",
    priorityAxes: ["RAM", "CS", "MON_S", "MON_C", "SSD_C"],
    officialMinimumGuide: {
      cpu: "최신 브라우저가 안정적으로 실행되는 기본 CPU 기준.",
      ram: "간단한 웹 탐색은 낮은 RAM에서도 가능하지만, 탭이 많아지면 부족할 수 있습니다.",
      gpu: "기본 화면 출력과 브라우저 가속이 가능한 내장 그래픽으로도 충분한 경우가 많습니다.",
      vram: "고용량 VRAM은 핵심 조건이 아닙니다.",
      storage: "다운로드 자료, 이미지, PDF, 스크린샷을 저장할 공간이 필요합니다.",
      monitor: "일반 모니터에서도 가능하지만, 여러 창을 띄우는 작업에는 화면 공간이 중요합니다.",
      note: "웹/레퍼런스 중심 작업은 고성능 GPU보다 브라우저 안정성, RAM, 모니터 공간이 더 중요합니다.",
    },
    practicalComfortGuide: {
      cpu: "브라우저 탭을 많이 열고 디자인 툴과 오갈 경우 최신 보급형~중급 CPU가 적합합니다.",
      ram: "여러 탭, 이미지 보드, 노션/피그마/문서 작업을 함께 쓰면 16GB보다 32GB가 안정적입니다.",
      gpu: "고성능 GPU는 필요하지 않고, 최신 내장 그래픽이나 보급형 GPU로 충분한 경우가 많습니다.",
      vram: "레퍼런스 수집 중심이라면 VRAM보다 RAM과 모니터 작업 공간이 더 중요합니다.",
      storage: "스크린샷, 이미지, PDF, 자료 파일을 많이 저장한다면 1TB SSD가 관리하기 편합니다.",
      monitor: "브라우저, 레퍼런스, 문서, 작업창을 함께 보기 위해 27인치 QHD 또는 듀얼 모니터가 유리합니다.",
      note: "웹/레퍼런스 작업은 본체 고성능보다 넓고 선명한 화면, 충분한 RAM, 자료 정리용 저장공간이 체감됩니다.",
    },
    overkillWarning: "웹 리서치와 레퍼런스 수집 중심이라면 고급 CPU나 GPU보다 RAM, 모니터 공간, 저장공간에 예산을 두는 편이 낫습니다.",
    designerExplanation: {
      RAM: "탭과 자료를 많이 열어둘 때 브라우저가 버벅이지 않도록 해줍니다.",
      CS: "브라우저, 문서, 디자인 툴을 오갈 때의 반응성에 영향을 줍니다.",
      MON_S: "자료와 작업창을 동시에 펼쳐두는 데 중요합니다.",
      MON_C: "레퍼런스 이미지의 색과 디테일을 확인하는 데 도움이 됩니다.",
      SSD_C: "수집한 이미지, PDF, 스크린샷이 쌓일 때 저장공간 여유를 만듭니다.",
    },
    sourceNote: "초기 mock 데이터. 브라우저 요구사항과 실제 디자이너 레퍼런스 작업 패턴으로 추가 검증 필요.",
  },
};

window.cpuMasterProgramSpecs = {
  programSpecKeyMap,
  programSpecGuides,
};
